# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  azurewebapideployment:
    image: azurewebapideployment
    build:
      context: .
      dockerfile: AzureWebAPIDeployment/Dockerfile
    ports:
      - 5097:5097
